<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>AstcSharp</PackageId>
    <Authors>Erik White</Authors>
    <Description>A library for encoding and decoding ASTC (Adaptive Scalable Texture Compression) compressed data.</Description>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Erik-White/AstcSharp</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Erik-White/AstcSharp</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>astc;texture;compression;decompression;graphics;rgba;decoder;encoder</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>AstcSharp.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AstcSharp.Tests, PublicKey=002400000480000094000000060200000024000052534131000400000100010079f4be8e8826d9fe6383926fe0e907187c555b79906c681eea1d9fdf9b6f3d1fae25c36af15aba6c1554ede9f58662eab23728e8dac40d0a97c92d5fd6c9befb831f8a6662320e2ce506945c7948420f0636d5ff4605e89dbe304cfcbdcfe28285b90afdabc2203cc5e2b037f4763c4ab182ccbe485778694fd9438e9e7d54c0" />
    <InternalsVisibleTo Include="AstcSharp.Benchmarks, PublicKey=002400000480000094000000060200000024000052534131000400000100010079f4be8e8826d9fe6383926fe0e907187c555b79906c681eea1d9fdf9b6f3d1fae25c36af15aba6c1554ede9f58662eab23728e8dac40d0a97c92d5fd6c9befb831f8a6662320e2ce506945c7948420f0636d5ff4605e89dbe304cfcbdcfe28285b90afdabc2203cc5e2b037f4763c4ab182ccbe485778694fd9438e9e7d54c0" />
    <InternalsVisibleTo Include="AstcSharp.Reference.Tests, PublicKey=002400000480000094000000060200000024000052534131000400000100010079f4be8e8826d9fe6383926fe0e907187c555b79906c681eea1d9fdf9b6f3d1fae25c36af15aba6c1554ede9f58662eab23728e8dac40d0a97c92d5fd6c9befb831f8a6662320e2ce506945c7948420f0636d5ff4605e89dbe304cfcbdcfe28285b90afdabc2203cc5e2b037f4763c4ab182ccbe485778694fd9438e9e7d54c0" />
  </ItemGroup>

</Project>
