<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\AstcSharp\AstcSharp.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.12" />
    <ProjectReference Include="../AstcSharp/AstcSharp.csproj" />
  </ItemGroup>

</Project>
